"""CREATE TABLE BATCH_FUTURE_BOOKMARK
   (RESTART_NAME STRING(1024), 
    THREAD_ID STRING(1024),
	THREAD_VAL STRING(1024), 
	BOOKMARK_STRING STRING(1024), 
	APPLICATION_IMAGE STRING(1024), 
	OUT_FILE_STRING STRING(1024), 
	NON_FATAL_ERR_FLAG STRING(1024), 
	NUM_COMMITS INT64, 
	AVG_TIME_BTWN_COMMITS INT64
   ) PRIMARY KEY (RESTART_NAME,THREAD_ID)"""