"""CREATE TABLE BATCH_FUTURE_PROGRAM_STATUS
   (RESTART_NAME STRING(1024),
    THREAD_ID STRING(1024), 
	THREAD_VAL STRING(1024), 
	START_TIME DATE, 
	PROGRAM_NAME STRING(1024), 
	PROGRAM_STATUS STRING(1024), 
	RESTART_FLAG BYTES(1), 
	RESTART_TIME DATE, 
	FINISH_TIME DATE, 
	CURRENT_PID INT64, 
	CURRENT_OPERATOR_ID STRING(1024), 
	ERR_MESSAGE STRING(1024)
   ) PRIMARY KEY (RESTART_NAME,THREAD_ID)"""