"""CREATE TABLE BATCH_FUTURE_CONTROL
        (   PROGRAM_NAME STRING(1024), 
            PROGRAM_DESC STRING(1024), 
            DRIVER_NAME STRING(1024), 
            NUM_THREADS INT64, 
            UPDATE_ALLOWED STRING(1024), 
            PROCESS_FLAG BYTES(1), 
            COMMIT_MAX_CTR INT64, 
            LOCK_WAIT_TIME INT64, 
            RETRY_MAX_CTR INT64
        ) PRIMARY KEY (PROGRAM_NAME)"""